version: "2"

services:
  sut:
    build: .
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-getting-started.git
      - SERVER_PROFILE_PATH=pingdirectory
    command: start-server /opt/wait-for localhost:389 -t 300 -- ldapsearch -b "dc=example,dc=com" -s base '(&)' 1.1
